"""delete email in User

Revision ID: 942fae975d0d
Revises: 714ceab1d37a
Create Date: 2025-02-21 16:57:10.421014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942fae975d0d'
down_revision: Union[str, None] = '714ceab1d37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_email', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
